name: Merge Dev into Main every 10 minutes

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set Mail
      run: git config --global user.email "timseferagic@gmail.com"
    
    - name: Set Name
      run: git config --global user.name "Tim"

    - name: Fetch branches
      run: git fetch

    - name: Checkout main branch
      run: git checkout main

    - name: Merge dev branch
      run: git merge origin/dev --allow-unrelated-histories
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
